// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using product_catalog_app.src.data;

#nullable disable

namespace ProductCatalogApp.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250904132732_AddNewBarcodeFields")]
    partial class AddNewBarcodeFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("product_catalog_app.src.models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("product_catalog_app.src.models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmazonBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("BataryaCikisUcuUzunlugu")
                        .HasColumnType("TEXT");

                    b.Property<string>("BataryaYuksekligi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Depth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EanCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HaceyapiBarcode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("HepsiburadaBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HepsiburadaSellerStockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HepsiburadaTedarikBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl10")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl9")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KabinTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KlozetKanalYapisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KlozetKapakCinsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KlozetMontajTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KlozetTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasEanBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasEanIstanbulBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasIstanbulBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawaboArmaturDeligi")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawaboOzelligi")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawaboSuTasmaDeligi")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawaboTipi")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LogoBarcodes")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("N11CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("N11ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PazaramaBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PttAvmBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PttUrunStokKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode1")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode2")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode3")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode4")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendyolBarcode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrls")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Category");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.HasIndex("SKU");

                    b.HasIndex("Category", "Brand");

                    b.HasIndex("IsArchived", "Name");

                    b.HasIndex("IsArchived", "Category", "Brand");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("product_catalog_app.src.models.ProductXml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmazonBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Depth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionPlain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EanCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HaceyapiBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("HepsiburadaBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HepsiburadaTedarikBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl1")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl10")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl4")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl5")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl6")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl7")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl8")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl9")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KoctasBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasEanBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasEanIstanbulBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KoctasIstanbulBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoBarcodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl10")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceImageUrl9")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PazaramaBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PttAvmBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PttUrunStokKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareBarcode4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendyolBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("XmlProducts");
                });

            modelBuilder.Entity("product_catalog_app.src.models.Product", b =>
                {
                    b.HasOne("product_catalog_app.src.models.Category", "CategoryEntity")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoryEntity");
                });

            modelBuilder.Entity("product_catalog_app.src.models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
